interest.rate.months.0=4.0
interest.rate.months.3=4.5
interest.rate.months.6=5.5
interest.rate.months.12=6.5
tenure.months.default=12
interest.rate.default=6.5

daily.transfer.limit.new=0.0
daily.transfer.limit.standard=0.0
daily.transfer.limit.premium=0.0
daily.transfer.limit.privilege=0.0
