min.balance=0.0
inactive.months.threshold=2
interest.rate=3.00

daily.transfer.limit.new=100000.0
daily.transfer.limit.standard=500000.0
daily.transfer.limit.premium=1000000.0
daily.transfer.limit.privilege=2500000.0
